# Prevent kiro-cli-term from launching inside tmux panes
set-environment -g Q_TERM_TMUX 1

# Set Prefix Key

set -g prefix C-a
unbind C-b
bind C-a send-prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

set -g mouse on
set -g set-clipboard on

# Status Bar

set -g status-bg cyan
set -g window-status-current-style bg=red,fg=white
set -g window-status-style bg=yellow

set-option -g status-position "bottom"
# set-option -g status-style bg=#282828,fg=#ebdbb2
# set-option -g status-justify left

# Colors and Theme
set -g default-terminal "screen-256color"
# set -ga terminal-overrides ",xterm-256color:Tc"

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
