# include classpath("application.conf")

akka.http.server.request-timeout = 40 s

node-address {
    protocol = http
    port = 9324
    host = sqs
    context-path = ""
}

rest-stats {
    enabled = true
    bind-port = 9325
    bind-hostname = "0.0.0.0"
}

queues {
    queue-stnd-test {
     delay = 5 seconds
     defaultVisibilityTimeout = 10 seconds
     fifo = false
     receiveMessageWait = 20 seconds
     deadLettersQueue {
       name = "sqs-dlq-stnd-test"
       maxReceiveCount = 3
     }
    }

    sqs-dlq-stnd-test {}
}

queues-storage {
    enabled = true
    path = "/data/queues.conf"
}

messages-storage {
    enabled = true
}

aws {
    region = us-east-1
    accountId = 000000000000
}