require("pavan.plugins-setup")

require("pavan.core.options")
require("pavan.core.keymaps")
require("pavan.core.colorscheme")
require("pavan.plugins.comment")
require("pavan.plugins.nvim-tree")
require("pavan.plugins.lualine")
require("pavan.plugins.telescope")
require("pavan.plugins.nvim-cmp")
require("pavan.plugins.lsp.mason")
require("pavan.plugins.lsp.lspconfig")
require("pavan.plugins.lsp.lspsaga")
require("pavan.plugins.lsp.null-ls")
require("pavan.plugins.lsp.mason-null-ls")
require("pavan.plugins.treesitter")
require("pavan.plugins.autopairs")
require("pavan.plugins.autotag")
